global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using KirikuuApp.Models;
global using KirikuuApp.Presentation;
global using KirikuuApp.DataContracts;
global using KirikuuApp.DataContracts.Serialization;
global using KirikuuApp.Services.Caching;
global using KirikuuApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
